Add controllers
KirSkl/java-shareit pull request #1
Opened 2023-07-09 10:04 UTC by KirSkl

2023-07-10 07:46 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые надо исправить!

Желаю удачи!

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    private Long id;
Сюда можно добавить аннотацию `Positive`

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
> +@Data
Нет никакой необходимости в этой аннотации. Это же просто класс с одним статичным методом.
 
 Более того, я бы посоветовал скрыть публичный конструктор без аргументов, сделав его приватным
 https://www.baeldung.com/java-sonar-hide-implicit-constructor

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    UserStorage userStorage;
модификаторы доступа

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        return usersDto;
Можно сделать тоже самое без перекладывания элементов:

```java
return userStorage.getAll()
                              .stream()
                              .map(UserMapper::toUserDto)
                              .collect(Collectors.toList());
```

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserInMemoryStorage.java
> +        if (users.containsKey(id)) {
Можно инвертировать условие, и не будет необходимости в операторе `else`, и можно будет сократить уровень вложенности

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserInMemoryStorage.java
> +        if (users.containsKey(id)) {
1. Аналогично тому, что ниже написал про инверсию
2. Эту проверку можно вынести в отдельный метод, чтобы постоянно не дублировать код, так как обрабатываем ее мы везде одинаково

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    Validator validator;
модификаторы доступа

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
Аналогичное замечание про публичный конструктор

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return searchResult;
можно так же обойтись с помощью `Stream API`

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    ItemStorage itemStorage;
модификаторы доступа

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemInMemoryStorage.java
> +        String searchText = text.toLowerCase();
я бы советовал еще пробелы в начале и концце строки удалить

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/common/Validator.java
> +            }
В этом нет смысла, метод `validateDuplicateEmail` не выкинет исключения, если список пустой.

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/common/Validator.java
> +        if (user.getEmail() != null) {
Лучше инверсировать условие, чтобы сократить уровень вложенности

2023-07-10 07:46 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/common/Validator.java
> +                u -> u.getEmail().equals(user.getEmail()))) {
Тут надо сравнивать без учета регистра. Так как идентичный адрес электронной почты, написанный в разных регистрах - идентичен.

2023-07-10 15:42 UTC, KirSkl commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    UserStorage userStorage;
Надеюсь, я когда-нибудь перестану о них забывать(

2023-07-11 16:34 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2023-07-11 16:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/common/Validator.java
> +    private UserStorage userStorage;
Модификатор `final` стоит добавить

2023-07-17 18:27 UTC, merged