Add item requests
KirSkl/java-shareit pull request #3
Opened 2023-08-27 16:07 UTC by KirSkl

2023-08-31 05:42 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара мелких замечаний, которые можно исправить!

Желаю удачи!

2023-08-31 05:42 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/user/UserServiceImplIntegrationTest.java
> +    private final UserService service;
Нет необходимости в модификаторах доступа в тестовых классах

2023-08-31 05:42 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>          userRepository.deleteById(id);
Если этот сервис обращается в СУБД, то это не лучший вариант. В идеале, при обновлении можно узнать сколько записей обновил запрос. В твоем случае это либо 0, либо 1, что

- очень похоже на значение битов

- позволяет понять, что если вернулся 0, то значит запись с указанным идентификатором была не найдена и можно выбросить исключение. Таким образом количество запросов к хранилищу уменьшится, а быстродействие метода повысится

2023-08-31 05:42 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +    private ItemRepository itemRepository;
Этим полям не хватает модификатора `final`

2023-08-31 17:33 UTC, KirSkl commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>          userRepository.deleteById(id);
К сожалению, пока не получилось это исправить. Метод deleteById() - возвращает void.
Пробовал прописывать метод с кастомным названием и типом возвращаемого значения int, и @Query запрос по совету наставника, как здесь https://stackoverflow.com/questions/39796849/spring-repository-get-number-of-deleted-rows
Но ничего не работает, к сожалению. Могу реализовать через try catch, если это предпочтительнее. Но если расскажешь, какую реализацию ты имел в виду, буду благодарен!

2023-09-01 07:19 UTC, LexLippi commented
Привет, отличная работа!

Желаю удачи в следующих спринтах!

2023-09-04 18:29 UTC, merged